### ISSUE TITLE
It is possible to select a leaf as the ingroup node

### ISSUE THREAD

**Issue by bredelings** [OpenTreeOfLife/opentree#1173]
This happened in ot_1463@Tr71674.  I'm not completely sure this should be forbidden by the user interface.

The issue is that it made propinquity die with:
```
prune_to_clean_mapped.py: Illegal root node "Tn11210679"
Traceback (most recent call last):
  File "/home/bredelings/Devel/OpenTree/peyotl/scripts/nexson/prune_to_clean_mapped.py", line 506, in <module>
    id_to_other_prune_reason=to_prune_for_reasons)
  File "/home/bredelings/Devel/OpenTree/peyotl/scripts/nexson/prune_to_clean_mapped.py", line 316, in prune_tree_for_supertree
    self.prune_to_ingroup()
  File "/home/bredelings/Devel/OpenTree/peyotl/scripts/nexson/prune_to_clean_mapped.py", line 127, in prune_to_ingroup
    self.root_node_id = self._ingroup_node_id
  File "/home/bredelings/Devel/OpenTree/peyotl/scripts/nexson/prune_to_clean_mapped.py", line 77, in set_root_node_id
    assert r in self._edge_by_source
AssertionError
```

I'll look into fixing the crash in propinquity.

**Comment by mtholder** [comment]
Agreed that the UI should not allow it. And the phylesystem-api code (backend of curator) should reject it.
The easiest fix is probably to go in and fix this study by hand in the curator, and work to prevent it from happening again.
I'm OK with propinquity exiting with a fatal error on this input.
