### ISSUE TITLE
Curator install fails due to some kind of ncl problem

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentree#630]
Not sure what repo to report this to, maybe ncl or peyotl is more appropriate? This is likely to be a deployment dependency issue.

    ...
    make[2]: Leaving directory '/home/opentree/repo/opentree/curator/build-ncl-static'
    make[1]: Leaving directory '/home/opentree/repo/opentree/curator/build-ncl-static'
    Apache / web2py restart required (due to app configuration)
    + make install
    + cd ..
    + grep ^\[external\] private/config
    + echo [external]
    + echo dir=/home/opentree/repo/opentree/curator/private/scratch
    + echo 2nexml=/home/opentree/repo/opentree/curator/private/bin/NCLconverter
    ERROR:root:code for hash md5 was not found.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
        globals()[__func_name] = __get_hash(__func_name)
      File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
        raise ValueError('unsupported hash type ' + name)
    ValueError: unsupported hash type md5
    ERROR:root:code for hash sha1 was not found.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
        globals()[__func_name] = __get_hash(__func_name)
      File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
        raise ValueError('unsupported hash type ' + name)
    ValueError: unsupported hash type sha1
    ERROR:root:code for hash sha224 was not found.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
        globals()[__func_name] = __get_hash(__func_name)
      File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
        raise ValueError('unsupported hash type ' + name)
    ValueError: unsupported hash type sha224
    ERROR:root:code for hash sha256 was not found.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
        globals()[__func_name] = __get_hash(__func_name)
      File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
        raise ValueError('unsupported hash type ' + name)
    ValueError: unsupported hash type sha256
    ERROR:root:code for hash sha384 was not found.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
        globals()[__func_name] = __get_hash(__func_name)
      File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
        raise ValueError('unsupported hash type ' + name)
    ValueError: unsupported hash type sha384
    ERROR:root:code for hash sha512 was not found.
    Traceback (most recent call last):
      File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
        globals()[__func_name] = __get_hash(__func_name)
      File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
        raise ValueError('unsupported hash type ' + name)
    ValueError: unsupported hash type sha512
    Traceback (most recent call last):
      File "/home/opentree/venv/bin/pip", line 9, in <module>
        load_entry_point('pip==1.1', 'console_scripts', 'pip')()
      File "/home/opentree/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 337, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/home/opentree/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2279, in load_entry_point
        return ep.load()
      File "/home/opentree/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load
        entry = __import__(self.module_name, globals(),globals(), ['__name__'])
      File "/home/opentree/venv/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/__init__.py", line 10, in <module>
        from pip.backwardcompat import walk_packages, console_to_str
      File "/home/opentree/venv/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/backwardcompat.py", line 18, in <module>
        import md5 as md5_module
      File "/usr/lib/python2.7/md5.py", line 10, in <module>
        from hashlib import md5
    ImportError: cannot import name md5

**Comment by jar398** [comment]
Sorry, forgot to mention that this is on ot17, following the Debian upgrade to 'jessie' (Debian 8). Not sure that the upgrade is connection to the errors, but it seems likely.

**Comment by mtholder** [comment]
I think that it is probably failing at https://github.com/OpenTreeOfLife/opentree/blob/master/deploy/setup/install-web2py-apps.sh#L136

the echo's are the very end of the install-ncl.sh script. and this looks like a pip issue (NCL does not use python for anything except testing, and does not use pip).

Recreating the virtualenv might be needed (virtualenv installs pip).

**Comment by jar398** [comment]
Thanks for thinking of that.  rm -r venv followed by redeploy seems to have
fixed the problem.

​

**Comment by jimallman** [comment]
Should/can we close this?
